name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET (Install Required Versions)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore HouseRentingSystem.sln

    - name: Build
      run: dotnet build HouseRentingSystem.sln --no-restore

    - name: Run Unit and Integration Tests
      run: dotnet test HouseRentingSystem.sln --no-build --verbosity normal
