name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore HouseRentingSystem.Services/HouseRentingSystem.sln

    - name: Build
      run: dotnet build HouseRentingSystem.Services/HouseRentingSystem.sln --no-restore

    - name: Run Unit and Integration Tests
      run: dotnet test HouseRentingSystem.Services/HouseRentingSystem.sln --no-build --verbosity normal
